{
 "title": "Histogram over all",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Replication time complete bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(miso_replication_time_complete_sum[$__rate_interval])) by (container)\r\n/\r\n  sum(rate(miso_replication_time_complete_count[$__rate_interval])) by (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replication Payload Size per Minute in KB (Container)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(miso_average_replication_size_sum[1m])) by (container) / (1024)\r\n\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Replication Time per targetNode",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "avg(rate(miso_replication_time_summary_sum[5m])) by (targetNode)\r\n/\r\navg(rate(miso_replication_time_summary_count[5m])) by (targetNode)",
     "legendFormat": "{{targetNode}}"
    }
   ]
  },
  {
   "title": "Requests per second / 1m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(miso_total_requests[1m])) by (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(miso_total_requests) by (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "avg(rate(miso_replication_time_all_bucket[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(miso_replication_time_bucket[$__rate_interval])) by (le, Node))",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}